export const mcpServerAppPackageName = "@task/mcp-server";

export {
  type AttachmentCreateLinkToolInput,
  type AttachmentListToolInput,
  type AttachmentToolHandlers,
  AttachmentToolInputError,
  createAttachmentToolHandlers,
  parseAttachmentCreateLinkToolInput,
  parseAttachmentListToolInput,
} from "./attachment-tools.js";

export {
  type ApplyTaskSkillResponse,
  type ArchiveProjectRequest,
  type ArchiveProjectResponse,
  type ArchiveTaskSkillRequest,
  type ArchiveTaskSkillResponse,
  type CancelConfirmationRequestRequest,
  type ConfirmationRequestDetailResponse,
  type ConfirmationRequestSummaryResponse,
  type ConfirmConfirmationRequestRequest,
  type ConfirmConfirmationRequestResponse,
  type CreateConfirmationRequestInput,
  type CreateConfirmationRequestRequest,
  type CreateProjectInput,
  type CreateProjectRequest,
  type CreateTaskCommentInput,
  type CreateTaskCommentRequest,
  type CreateTaskInput,
  type CreateTaskLinkAttachmentInput,
  type CreateTaskLinkAttachmentRequest,
  type CreateTaskRequest,
  type CreateTaskSkillInput,
  type CreateTaskSkillRequest,
  type CreateTaskSkillResponse,
  createTaskBackendClient,
  type GetConfirmationRequestRequest,
  type GetProjectRequest,
  type GetTaskRequest,
  type GetTaskSkillRequest,
  type GetWorkspaceRequest,
  type ListActiveProjectsRequest,
  type ListActiveTasksRequest,
  type ListPendingConfirmationRequestsRequest,
  type ListTaskAttachmentsRequest,
  type ListTaskCommentsRequest,
  type ListTaskSkillsRequest,
  type ListWorkspaceMembersRequest,
  type ListWorkspaceStatusesRequest,
  type ListWorkspacesRequest,
  type PreviewTaskSkillApplyInput,
  type PreviewTaskSkillApplyResponse,
  type ProjectDetailResponse,
  type ProjectSummaryResponse,
  type TaskAttachmentResponse,
  type TaskBackendClient,
  TaskBackendClientError,
  type TaskBackendClientOptions,
  type TaskBackendFetch,
  type TaskBackendFetchInit,
  type TaskBackendFetchResponse,
  type TaskBackendGetHeaders,
  type TaskBackendPostHeaders,
  type TaskCommentResponse,
  type TaskDetailResponse,
  type TaskSkillApplyRequest,
  type TaskSkillDetailResponse,
  type TaskSkillSummaryResponse,
  type TaskSummaryResponse,
  type UpdateProjectInput,
  type UpdateProjectRequest,
  type UpdateProjectResponse,
  type UpdateTaskAssigneeInput,
  type UpdateTaskAssigneeRequest,
  type UpdateTaskDueDateInput,
  type UpdateTaskDueDateRequest,
  type UpdateTaskSkillDefinitionInput,
  type UpdateTaskSkillDefinitionRequest,
  type UpdateTaskSkillDefinitionResponse,
  type UpdateTaskSkillMetadataInput,
  type UpdateTaskSkillMetadataRequest,
  type UpdateTaskSkillMetadataResponse,
  type UpdateTaskStatusInput,
  type UpdateTaskStatusRequest,
  type WorkspaceDetailResponse,
  type WorkspaceMemberResponse,
  type WorkspaceStatusResponse,
  type WorkspaceSummaryResponse,
} from "./backend-client.js";

export {
  type CommentCreateToolInput,
  type CommentListToolInput,
  type CommentToolHandlers,
  CommentToolInputError,
  createCommentToolHandlers,
  parseCommentCreateToolInput,
  parseCommentListToolInput,
} from "./comment-tools.js";
export {
  InvalidTaskMcpEnvironmentError,
  loadTaskMcpConfig,
  parseTaskMcpConfig,
  type TaskMcpConfig,
  type TaskMcpEnvironment,
} from "./config.js";
export {
  type ConfirmationCancelToolInput,
  type ConfirmationCommitToolInput,
  type ConfirmationCreateToolInput,
  type ConfirmationGetToolInput,
  type ConfirmationListPendingToolInput,
  type ConfirmationToolHandlers,
  ConfirmationToolInputError,
  createConfirmationToolHandlers,
  parseConfirmationCancelToolInput,
  parseConfirmationCommitToolInput,
  parseConfirmationCreateToolInput,
  parseConfirmationGetToolInput,
  parseConfirmationListPendingToolInput,
} from "./confirmation-tools.js";

export {
  connectTaskMcpServerToStdio,
  createTaskMcpServer,
  registerAttachmentTools,
  registerCommentTools,
  registerConfirmationTools,
  registerProjectTools,
  registerStatusTools,
  registerTaskSkillApplyTools,
  registerTaskTools,
  registerWorkspaceTools,
  type TaskMcpServerOptions,
  type TaskMcpToolRegistrar,
  type TaskSkillToolRegistrar,
} from "./mcp-server.js";
export {
  createProjectToolHandlers,
  type ProjectArchiveToolInput,
  type ProjectCreateToolInput,
  type ProjectGetToolInput,
  type ProjectSearchToolInput,
  type ProjectToolHandlers,
  ProjectToolInputError,
  type ProjectUpdateToolInput,
  parseProjectArchiveToolInput,
  parseProjectCreateToolInput,
  parseProjectGetToolInput,
  parseProjectSearchToolInput,
  parseProjectUpdateToolInput,
} from "./project-tools.js";
export {
  type RunTaskMcpServerOptions,
  runTaskMcpServerFromEnvironment,
  type TaskMcpServerConnector,
} from "./runtime.js";
export {
  createStatusToolHandlers,
  parseStatusListToolInput,
  type StatusListToolInput,
  type StatusToolHandlers,
  StatusToolInputError,
} from "./status-tools.js";
export {
  createTaskSkillToolHandlers,
  parseTaskSkillApplyToolInput,
  parseTaskSkillArchiveToolInput,
  parseTaskSkillCreateToolInput,
  parseTaskSkillGetToolInput,
  parseTaskSkillSearchToolInput,
  parseTaskSkillUpdateDefinitionToolInput,
  parseTaskSkillUpdateMetadataToolInput,
  type TaskSkillApplyToolInput,
  type TaskSkillArchiveToolInput,
  type TaskSkillCreateToolInput,
  type TaskSkillGetToolInput,
  type TaskSkillSearchToolInput,
  type TaskSkillToolHandlers,
  TaskSkillToolInputError,
  type TaskSkillUpdateDefinitionToolInput,
  type TaskSkillUpdateMetadataToolInput,
} from "./task-skill-tools.js";
export {
  createTaskToolHandlers,
  parseTaskCreateToolInput,
  parseTaskGetToolInput,
  parseTaskSearchToolInput,
  parseTaskSetAssigneeToolInput,
  parseTaskSetDueDateToolInput,
  parseTaskSetStatusToolInput,
  type TaskCreateToolInput,
  type TaskGetToolInput,
  type TaskSearchToolInput,
  type TaskSetAssigneeToolInput,
  type TaskSetDueDateToolInput,
  type TaskSetStatusToolInput,
  type TaskToolHandlers,
  TaskToolInputError,
} from "./task-tools.js";
export {
  createWorkspaceToolHandlers,
  parseWorkspaceGetCurrentToolInput,
  parseWorkspaceMemberListToolInput,
  type WorkspaceGetCurrentToolInput,
  type WorkspaceMemberListToolInput,
  type WorkspaceToolHandlers,
  WorkspaceToolInputError,
} from "./workspace-tools.js";
