export const mcpServerAppPackageName = "@task/mcp-server";

export {
  type AttachmentCreateLinkToolInput,
  type AttachmentListToolInput,
  type AttachmentToolHandlers,
  AttachmentToolInputError,
  createAttachmentToolHandlers,
  parseAttachmentCreateLinkToolInput,
  parseAttachmentListToolInput,
} from "./attachment-tools.js";

export {
  type ApplyTaskSkillResponse,
  type CreateProjectInput,
  type CreateProjectRequest,
  type CreateTaskCommentInput,
  type CreateTaskCommentRequest,
  type CreateTaskInput,
  type CreateTaskLinkAttachmentInput,
  type CreateTaskLinkAttachmentRequest,
  type CreateTaskRequest,
  createTaskBackendClient,
  type GetProjectRequest,
  type GetTaskRequest,
  type GetWorkspaceRequest,
  type ListActiveProjectsRequest,
  type ListActiveTasksRequest,
  type ListTaskAttachmentsRequest,
  type ListTaskCommentsRequest,
  type ListWorkspaceMembersRequest,
  type ListWorkspaceStatusesRequest,
  type ListWorkspacesRequest,
  type PreviewTaskSkillApplyInput,
  type PreviewTaskSkillApplyResponse,
  type ProjectDetailResponse,
  type ProjectSummaryResponse,
  type TaskAttachmentResponse,
  type TaskBackendClient,
  TaskBackendClientError,
  type TaskBackendClientOptions,
  type TaskBackendFetch,
  type TaskBackendFetchInit,
  type TaskBackendFetchResponse,
  type TaskBackendGetHeaders,
  type TaskBackendPostHeaders,
  type TaskCommentResponse,
  type TaskDetailResponse,
  type TaskSkillApplyRequest,
  type TaskSummaryResponse,
  type UpdateTaskAssigneeInput,
  type UpdateTaskAssigneeRequest,
  type UpdateTaskDueDateInput,
  type UpdateTaskDueDateRequest,
  type UpdateTaskStatusInput,
  type UpdateTaskStatusRequest,
  type WorkspaceDetailResponse,
  type WorkspaceMemberResponse,
  type WorkspaceStatusResponse,
  type WorkspaceSummaryResponse,
} from "./backend-client.js";

export {
  type CommentCreateToolInput,
  type CommentListToolInput,
  type CommentToolHandlers,
  CommentToolInputError,
  createCommentToolHandlers,
  parseCommentCreateToolInput,
  parseCommentListToolInput,
} from "./comment-tools.js";

export {
  InvalidTaskMcpEnvironmentError,
  loadTaskMcpConfig,
  parseTaskMcpConfig,
  type TaskMcpConfig,
  type TaskMcpEnvironment,
} from "./config.js";

export {
  connectTaskMcpServerToStdio,
  createTaskMcpServer,
  registerAttachmentTools,
  registerCommentTools,
  registerProjectTools,
  registerStatusTools,
  registerTaskSkillApplyTools,
  registerTaskTools,
  registerWorkspaceTools,
  type TaskMcpServerOptions,
  type TaskMcpToolRegistrar,
  type TaskSkillToolRegistrar,
} from "./mcp-server.js";
export {
  createProjectToolHandlers,
  type ProjectCreateToolInput,
  type ProjectGetToolInput,
  type ProjectSearchToolInput,
  type ProjectToolHandlers,
  ProjectToolInputError,
  parseProjectCreateToolInput,
  parseProjectGetToolInput,
  parseProjectSearchToolInput,
} from "./project-tools.js";
export {
  type RunTaskMcpServerOptions,
  runTaskMcpServerFromEnvironment,
  type TaskMcpServerConnector,
} from "./runtime.js";
export {
  createStatusToolHandlers,
  parseStatusListToolInput,
  type StatusListToolInput,
  type StatusToolHandlers,
  StatusToolInputError,
} from "./status-tools.js";
export {
  createTaskSkillToolHandlers,
  parseTaskSkillApplyToolInput,
  type TaskSkillApplyToolInput,
  type TaskSkillToolHandlers,
  TaskSkillToolInputError,
} from "./task-skill-tools.js";
export {
  createTaskToolHandlers,
  parseTaskCreateToolInput,
  parseTaskGetToolInput,
  parseTaskSearchToolInput,
  parseTaskSetAssigneeToolInput,
  parseTaskSetDueDateToolInput,
  parseTaskSetStatusToolInput,
  type TaskCreateToolInput,
  type TaskGetToolInput,
  type TaskSearchToolInput,
  type TaskSetAssigneeToolInput,
  type TaskSetDueDateToolInput,
  type TaskSetStatusToolInput,
  type TaskToolHandlers,
  TaskToolInputError,
} from "./task-tools.js";
export {
  createWorkspaceToolHandlers,
  parseWorkspaceGetCurrentToolInput,
  parseWorkspaceMemberListToolInput,
  type WorkspaceGetCurrentToolInput,
  type WorkspaceMemberListToolInput,
  type WorkspaceToolHandlers,
  WorkspaceToolInputError,
} from "./workspace-tools.js";
