export {
  isTelegramAgentInvocation,
  normalizeTelegramAgentInput,
  parseTelegramConfirmationCallbackContext,
  parseTelegramMessageContext,
  type TelegramAttachmentContext,
  type TelegramChatContext,
  type TelegramConfirmationCallbackAction,
  type TelegramConfirmationCallbackContext,
  type TelegramDocumentAttachmentContext,
  type TelegramMessageContext,
  type TelegramMessageEntityContext,
  type TelegramPhotoAttachmentContext,
  type TelegramReplyTarget,
  TelegramUpdateParseError,
  type TelegramUserContext,
} from "@task/integration-telegram";
