"use client";

import { Badge, Button, Card, Checkbox, Progress, Table, Tabs, Text } from "@radix-ui/themes";
import { ArrowUpRight, Bot, CheckCircle2, ChevronRight, Clock3, MoreHorizontal, Plus, Sparkles, Workflow } from "lucide-react";
import Link from "next/link";
import type { ReactNode } from "react";
import type { ProjectData, WorkspaceBootstrap } from "../lib/workspace-contracts";
import { useWorkspaceData } from "../lib/use-workspace-data";
import { useWorkspaceStore } from "../lib/workspace-store";
import { useSearchParams } from "next/navigation";

export type ViewKind = "dashboard" | "tasks" | "projects" | "project" | "kanban" | "matrix" | "table" | "templates" | "confirmations" | "history" | "settings" | "telegram";
const copy: Record<ViewKind, { title: string; subtitle: string }> = { dashboard:{title:"Дашборд",subtitle:"Обзор процессов рабочего пространства"},tasks:{title:"Мои задачи",subtitle:"Задачи, назначенные текущему пользователю"},projects:{title:"Проекты",subtitle:"Активные проекты рабочего пространства"},project:{title:"Проект",subtitle:"Задачи и прогресс проекта"},kanban:{title:"Канбан",subtitle:"Задачи сгруппированы по статусам"},matrix:{title:"Матрица",subtitle:"Этапы и задачи выбранного проекта"},table:{title:"Таблица",subtitle:"Плоский список задач выбранного проекта"},templates:{title:"Шаблоны",subtitle:"Task skills рабочего пространства"},confirmations:{title:"Подтверждения",subtitle:"Ожидающие решения действия агента"},history:{title:"История агента",subtitle:"Запуски агента в рабочем пространстве"},settings:{title:"Настройки",subtitle:"Участники и конфигурация рабочего пространства"},telegram:{title:"Настройки Telegram",subtitle:"Статус привязки Telegram доступен через backend API."}};

export function WorkspaceView({ kind, projectId }: Readonly<{ kind: ViewKind; projectId?: string }>): ReactNode {
  const { data, error, loading, refresh } = useWorkspaceData();
  const searchParams = useSearchParams();
  const setCreateOpen = useWorkspaceStore((state) => state.setCreateOpen);
  if (loading) return <Card className="panel"><Text color="gray">Загружаю данные рабочего пространства…</Text></Card>;
  if (error !== null || data === null) return <Card className="panel connection-error"><h2>Нет подключения к backend API</h2><p>{error ?? "Не удалось загрузить данные."}</p><code>TASK_API_BASE_URL=http://localhost:3000<br/>TASK_USER_ID=&lt;uuid пользователя&gt;</code><Button size="1" onClick={() => void refresh()}>Повторить</Button></Card>;
  const selectedProjectId = projectId ?? searchParams.get("project") ?? undefined;
  const title = kind === "project" && selectedProjectId !== undefined ? data.projects.find((project) => project.id === selectedProjectId)?.title ?? copy[kind].title : copy[kind].title;
  return <><div className="page-heading"><div><h1>{title}</h1><p>{copy[kind].subtitle}</p></div>{["projects", "templates"].includes(kind) && <Button size="1" onClick={() => setCreateOpen(true)}><Plus size={14}/> Создать</Button>}</div>{renderView(kind, data, selectedProjectId, refresh)}</>;
}

function renderView(kind: ViewKind, data: WorkspaceBootstrap, projectId: string | undefined, refresh: () => Promise<void>): ReactNode {
  const project = findProjectData(data, projectId);
  if (kind === "dashboard") return <Dashboard data={data}/>;
  if (kind === "tasks") return <Tasks data={data} refresh={refresh}/>;
  if (kind === "projects") return <Projects data={data}/>;
  if (kind === "project") return <ProjectDetail data={data} project={project}/>;
  if (kind === "kanban") return <Kanban data={data} project={project}/>;
  if (kind === "matrix") return <Matrix project={project}/>;
  if (kind === "table") return <TaskTable data={data} project={project}/>;
  if (kind === "templates") return <Templates data={data}/>;
  if (kind === "confirmations") return <Confirmations data={data} refresh={refresh}/>;
  if (kind === "history") return <History data={data}/>;
  if (kind === "settings") return <Settings data={data}/>;
  return <Telegram data={data}/>;
}
function findProjectData(data: WorkspaceBootstrap, projectId?: string): ProjectData | undefined { return data.projectData.find((item) => item.projectId === projectId) ?? data.projectData[0]; }
function Dashboard({ data }: Readonly<{ data: WorkspaceBootstrap }>): ReactNode { const c=data.dashboard.taskCounts; return <><section className="metrics">{[["Назначено",c.assigned,"indigo"],["Просрочено",c.overdue,"red"],["Скоро срок",c.dueSoon,"amber"],["Активные проекты",data.dashboard.activeProjects.length,"green"]].map(([title,value,color])=><Card key={String(title)} className="metric"><Text size="1" color="gray">{title}</Text><strong>{value}</strong><Progress value={Math.min(Number(value)*10,100)} color={color === "red" ? "red" : color === "amber" ? "amber" : color === "green" ? "green" : "indigo"}/></Card>)}</section><section className="two-columns"><Card className="panel"><PanelTitle title="Мои задачи"/><TaskRows data={data} items={data.myTasks.items.slice(0,5)}/></Card><Card className="panel"><PanelTitle title="Активные проекты"/>{data.dashboard.activeProjects.map((project)=><Link className="project-row" href={`/projects/${project.id}`} key={project.id}><span className="project-dot">{project.title.slice(0,1)}</span><div><strong>{project.title}</strong><small>{project.status ?? "Без статуса"}</small></div><ChevronRight size={16}/></Link>)}</Card></section><Card className="agent-callout"><Sparkles size={20}/><div><strong>Последние запуски агента</strong><p>{data.dashboard.recentAgentRuns.at(0)?.inputText ?? "Запусков ещё не было."}</p></div><Badge>{data.dashboard.pendingConfirmations.length} ожид.</Badge></Card></> }
function Tasks({ data, refresh }: Readonly<{ data: WorkspaceBootstrap; refresh: () => Promise<void> }>): ReactNode { return <Card className="panel"><PanelTitle title={`Всего: ${data.myTasks.total}`}/><TaskRows data={data} items={data.myTasks.items} refresh={refresh}/></Card> }
function TaskRows({ data, items, refresh }: Readonly<{ data: WorkspaceBootstrap; items: WorkspaceBootstrap["myTasks"]["items"]; refresh?: () => Promise<void> }>): ReactNode { const done = data.statuses.find((status)=>status.isDone); return <>{items.map((task)=><div className="task-row" key={task.id}><Checkbox checked={done?.id === task.statusId} onCheckedChange={() => { if (done !== undefined && refresh !== undefined) void updateTaskStatus(data.workspace.id, task.projectId, task.id, done.id, refresh); }}/><div><strong>{task.title}</strong><small>{task.projectTitle}</small></div><Badge color="gray">{task.statusName ?? "Без статуса"}</Badge><span>{formatDate(task.dueAt)}</span></div>)}</> }
function Projects({ data }: Readonly<{ data: WorkspaceBootstrap }>): ReactNode { return <div className="project-grid">{data.projects.map((project)=><Link href={`/projects/${project.id}`} key={project.id} className="project-card"><div><span className="cover">{project.title.slice(0,1)}</span><Badge color="indigo">{project.status ?? "Активный"}</Badge></div><h2>{project.title}</h2><p>{project.description ?? "Описание не задано"}</p><small>Обновлено {formatDate(project.updatedAt)}</small></Link>)}</div> }
function ProjectDetail({ data, project }: Readonly<{ data: WorkspaceBootstrap; project: ProjectData | undefined }>): ReactNode { if (project === undefined) return <Empty text="В рабочем пространстве пока нет проектов."/>; return <><Tabs.Root defaultValue="tasks"><Tabs.List><Tabs.Trigger value="tasks">Задачи</Tabs.Trigger><Tabs.Trigger value="matrix">Матрица</Tabs.Trigger></Tabs.List></Tabs.Root><Card className="panel"><PanelTitle title={`Задачи: ${project.tasks.length}`}/>{project.tasks.map((task)=><div className="task-row" key={task.id}><CheckCircle2 size={16}/><div><strong>{task.title}</strong><small>{task.description ?? "Без описания"}</small></div><span>{formatDate(task.dueAt ?? null)}</span></div>)}</Card></> }
function Kanban({ data, project }: Readonly<{ data: WorkspaceBootstrap; project: ProjectData | undefined }>): ReactNode { if (project === undefined) return <Empty text="Выберите проект, чтобы увидеть канбан."/>; const tasksWithoutStatus = project.tasks.filter((task)=>task.statusId === null); return <div className="board">{data.statuses.map((status)=>{const tasks = project.tasks.filter((task)=>task.statusId === status.id); return <KanbanColumn key={status.id} title={status.name} tasks={tasks}/>})}{tasksWithoutStatus.length > 0 && <KanbanColumn title="Без статуса" tasks={tasksWithoutStatus}/>}</div> }
function KanbanColumn({ title, tasks }: Readonly<{ title: string; tasks: ProjectData["tasks"] }>): ReactNode { return <section><div className="board-heading"><strong>{title}</strong><Badge>{tasks.length}</Badge></div>{tasks.map((task)=><Card key={task.id} className="kanban-card"><strong>{task.title}</strong><small>{task.description ?? "Без описания"}</small></Card>)}</section> }
function Matrix({ project }: Readonly<{ project: ProjectData | undefined }>): ReactNode { if (project === undefined) return <Empty text="Выберите проект, чтобы увидеть матрицу."/>; return <Card className="panel matrix"><div className="matrix-grid matrix-head"><span>Этап</span>{project.matrix.columns.map((column)=><span key={column.id}>{column.title}</span>)}</div>{project.matrix.stages.map((stage)=><div className="matrix-grid" key={stage.position}><strong>{stage.name}</strong>{project.matrix.columns.map((column)=>{const cell=project.matrix.cells.find((item)=>item.columnTaskId===column.id && item.stageId===stage.id); return <span className="matrix-cell active" key={column.id}>{cell?.tasks.map((task)=>task.title).join(", ") ?? ""}</span>;})}</div>)}</Card> }
function TaskTable({ data, project }: Readonly<{ data: WorkspaceBootstrap; project: ProjectData | undefined }>): ReactNode { if(project===undefined)return <Empty text="Выберите проект, чтобы увидеть таблицу."/>; return <Card className="table-card"><Table.Root><Table.Header><Table.Row><Table.ColumnHeaderCell>Задача</Table.ColumnHeaderCell><Table.ColumnHeaderCell>Срок</Table.ColumnHeaderCell><Table.ColumnHeaderCell>Описание</Table.ColumnHeaderCell><Table.ColumnHeaderCell/></Table.Row></Table.Header><Table.Body>{project.table.items.map((task)=><Table.Row key={task.id}><Table.RowHeaderCell>{task.title}</Table.RowHeaderCell><Table.Cell>{formatDate(task.dueAt ?? null)}</Table.Cell><Table.Cell>{task.description ?? "—"}</Table.Cell><Table.Cell><MoreHorizontal size={16}/></Table.Cell></Table.Row>)}</Table.Body></Table.Root></Card> }
function Templates({ data }: Readonly<{ data: WorkspaceBootstrap }>): ReactNode { return <div className="template-grid">{data.taskSkills.map((skill)=><Card className="template-card" key={skill.id}><Workflow size={22}/><h2>{skill.name}</h2><p>{skill.description ?? "Без описания"}</p><small>{skill.aliases.join(", ") || "Нет алиасов"}</small></Card>)}</div> }
function Confirmations({ data, refresh }: Readonly<{ data: WorkspaceBootstrap; refresh: () => Promise<void> }>): ReactNode { return <div className="stacked">{data.confirmations.map((confirmation)=><Card className="confirmation" key={confirmation.id}><div><span className="agent-icon"><Bot size={18}/></span><strong>{confirmation.kind}</strong><p>Истекает {formatDate(confirmation.expiresAt)}</p></div><div><Button variant="soft" color="gray" size="1" onClick={()=>void updateConfirmation(data.workspace.id,confirmation.id,"cancel",refresh)}>Отклонить</Button><Button size="1" onClick={()=>void updateConfirmation(data.workspace.id,confirmation.id,"confirm",refresh)}>Подтвердить</Button></div></Card>)}</div> }
function History({ data }: Readonly<{ data: WorkspaceBootstrap }>): ReactNode { return <Card className="panel timeline">{data.agentRuns.map((run)=><div key={run.id}><span className="timeline-dot"/><strong>{run.inputText}</strong><small>{run.source} · {run.status} · {formatDate(run.createdAt)}</small><p>{run.finalResponse ?? run.error ?? "Выполняется"}</p></div>)}</Card> }
function Settings({ data }: Readonly<{ data: WorkspaceBootstrap }>): ReactNode { return <section className="settings"><Card className="panel"><PanelTitle title="Рабочее пространство"/><label>Название<input value={data.workspace.name} readOnly/></label><label>Slug<input value={data.workspace.slug} readOnly/></label></Card><Card className="panel"><PanelTitle title="Участники"/>{data.workspace.members.map((member)=><div className="person" key={member.id}><span className="avatar">{member.displayName.slice(0,1)}</span><span><strong>{member.displayName}</strong><small>{member.role}</small></span></div>)}</Card></section> }
function Telegram({ data }: Readonly<{ data: WorkspaceBootstrap }>): ReactNode { return <Card className="panel"><PanelTitle title="Telegram Mini App"/><p>Для Telegram backend предоставляет проверку initData и статус привязки identity. Настройки каналов и bot permissions пока не входят в опубликованный API-контракт.</p><Text size="2" color="gray">Workspace: {data.workspace.name}</Text></Card> }
function Empty({ text }: Readonly<{ text: string }>): ReactNode { return <Card className="panel"><Text color="gray">{text}</Text></Card> }
function PanelTitle({ title }: Readonly<{ title: string }>): ReactNode { return <div className="panel-title"><h2>{title}</h2><Clock3 size={16}/></div> }
function formatDate(value: string | null | undefined): string { return value === null || value === undefined ? "—" : new Intl.DateTimeFormat("ru-RU", { day:"2-digit", month:"short" }).format(new Date(value)); }
async function updateTaskStatus(workspaceId: string, projectId: string, taskId: string, statusId: string, refresh: () => Promise<void>): Promise<void> { await fetch(`/api/workspace/tasks/${taskId}`, { method:"PATCH", headers:{"content-type":"application/json"}, body:JSON.stringify({workspaceId,projectId,statusId}) }); await refresh(); }
async function updateConfirmation(workspaceId: string, confirmationId: string, action: "cancel" | "confirm", refresh: () => Promise<void>): Promise<void> { await fetch(`/api/workspace/confirmations/${confirmationId}`, { method:"PATCH", headers:{"content-type":"application/json"}, body:JSON.stringify({workspaceId,action}) }); await refresh(); }
