export const apiClientPackageName = "@task/api-client";

export {
  type AgentRunSummary,
  type ArchiveProjectRequestInput,
  type ArchiveProjectResponse,
  type ArchiveTaskRequestInput,
  type ConfirmationRequestDetail,
  type ConfirmationRequestScopedInput,
  type ConfirmationRequestSummary,
  type CreateProjectInput,
  type CreateProjectRequestInput,
  type CreateTaskCommentInput,
  type CreateTaskCommentRequestInput,
  type CreateTaskFileAttachmentInput,
  type CreateTaskFileAttachmentRequestInput,
  type CreateTaskInput,
  type CreateTaskLinkAttachmentInput,
  type CreateTaskLinkAttachmentRequestInput,
  type CreateTaskRequestInput,
  type CreateTaskTelegramFileAttachmentInput,
  type CreateTaskTelegramFileAttachmentRequestInput,
  createTaskApiClient,
  type DashboardOverview,
  type HealthResponse,
  type ListMyTasksRequestInput,
  type MyTasksPage,
  type ProjectDetail,
  type ProjectScopedInput,
  type ProjectSummary,
  type TaskApiClient,
  TaskApiClientError,
  type TaskApiClientOptions,
  type TaskApiFetch,
  type TaskApiRequestHeaders,
  type TaskApiRequestInit,
  type TaskApiResponse,
  type TaskAttachment,
  type TaskComment,
  type TaskDetail,
  type TaskScopedInput,
  type TaskSkillSummary,
  type TaskSummary,
  type UpdateProjectInput,
  type UpdateProjectRequestInput,
  type UpdateProjectResponse,
  type UpdateTaskInput,
  type UpdateTaskRequestInput,
  type UpdateTaskResponse,
  type WorkspaceScopedInput,
  type WorkspaceStatus,
  type WorkspaceSummary,
} from "./client.js";
export type { components, operations, paths } from "./generated/openapi.js";
